version: '3.5'

services:
  
  frontend:
    image: node:18.16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true
    command: >
      sh -c "yarn 
      && yarn next telemetry disable
      && yarn dev"
  

volumes:
  maria-data:
    driver: local 